spring:
  datasource:
    url: jdbc:mysql://localhost:3306/switch_and_trade
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: admin@gmail.com
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          ssl:
            trust: smtp.gmail.com


